const QUOTES = [
  { text: "Zähle nicht die Tage. Sorge dafür, dass jeder Tag zählt.", author: "Muhammad Ali" },
  { text: "Schmerz ist vorübergehend. Aufgeben ist für immer.", author: "" },
  { text: "Was dich nicht umbringt, macht dich stärker.", author: "Friedrich Nietzsche" },
  { text: "Harte Arbeit schlägt Talent, wenn Talent nicht hart arbeitet.", author: "Tim Notke" },
  { text: "Vertraue dem Prozess. Die Ergebnisse folgen.", author: "" },
  { text: "Dein Körper kann fast alles. Es ist dein Geist, den du überzeugen musst.", author: "" },
  { text: "Die härteste Arbeit ist die, die du tust, wenn niemand zuschaut.", author: "" },
  { text: "Jede Wiederholung bringt dich deinem Ziel näher.", author: "" },
  { text: "Heute tust du, was andere nicht wollen. Morgen kannst du, was andere nicht können.", author: "" },
  { text: "Fortschritt, nicht Perfektion.", author: "" },
  { text: "Ein bisschen Fortschritt jeden Tag summiert sich zu großen Ergebnissen.", author: "Robert Collier" },
  { text: "Wenn du aufgeben willst, erinnere dich daran, warum du angefangen hast.", author: "" },
  { text: "Komfort ist der Feind des Fortschritts.", author: "" },
  { text: "Jeder Champion war einmal ein Anfänger.", author: "" },
  { text: "Stärke kommt nicht aus körperlicher Kapazität. Sie kommt aus einem unbeugsamen Willen.", author: "Mahatma Gandhi" },
  { text: "Erfolg ist die Summe kleiner Bemühungen, täglich wiederholt.", author: "Robert Collier" },
  { text: "Die Disziplin von heute ist die Stärke von morgen.", author: "" },
  { text: "Dein zukünftiges Ich dankt dir für das, was du heute tust.", author: "" },
  { text: "Der Geist gibt auf, lange bevor der Körper es tut.", author: "" },
  { text: "Nicht wie du anfängst, sondern wie du endest, definiert dich.", author: "" },
  { text: "Jeder Tag ist eine neue Chance, der Mensch zu werden, der du sein willst.", author: "" },
  { text: "Gewinner hören nicht auf. Aufhörer gewinnen nicht.", author: "" },
  { text: "Das Geheimnis des Erfolgs ist, anzufangen.", author: "Mark Twain" },
  { text: "Es gibt keine Abkürzungen zu einem Ziel, das es wert ist zu erreichen.", author: "" },
  { text: "Kleine tägliche Verbesserungen führen zu atemberaubenden Ergebnissen.", author: "" },
  { text: "Der Körper erreicht, was der Geist glaubt.", author: "" },
  { text: "Stark sein ist die einzige Option.", author: "" },
  { text: "90 Tage. Konsequent. Kein Kompromiss.", author: "" },
  { text: "Du bist nicht hier, um durchschnittlich zu sein.", author: "" },
  { text: "Wer aufhört, besser zu werden, hat aufgehört, gut zu sein.", author: "" },
  { text: "Mach es, auch wenn du keine Lust hast. Besonders dann.", author: "" },
  { text: "Veränderung passiert außerhalb deiner Komfortzone.", author: "" },
  { text: "Dein Körper ist das Ergebnis deiner täglichen Entscheidungen.", author: "" },
  { text: "Konsistenz schlägt Intensität. Immer.", author: "" },
  { text: "Schweiß ist Fett, das weint.", author: "" },
  { text: "Disziplin ist Freiheit.", author: "Jocko Willink" },
  { text: "Die Schmerzen der Disziplin wiegen nie so schwer wie der Schmerz der Reue.", author: "" },
  { text: "Wähle die Unbequemlichkeit heute oder bereue die Bequemlichkeit morgen.", author: "" },
  { text: "Selbstdisziplin ist das höchste Zeichen von Selbstliebe.", author: "" },
  { text: "Dein Wille ist stärker als dein Gefühl.", author: "" },
  { text: "Energie folgt dem Fokus.", author: "" },
  { text: "Der beste Zeitpunkt war gestern. Der zweitbeste ist jetzt.", author: "" },
  { text: "Jede Mahlzeit ist eine Entscheidung für deinen Körper.", author: "" },
  { text: "Dein Körper ist das ehrlichste Tagebuch, das du führst.", author: "" },
  { text: "Die härtesten Tage sind die wichtigsten.", author: "" },
  { text: "Durchhalten ist eine Superkraft.", author: "" },
  { text: "Heute wieder. Immer wieder.", author: "" },
  { text: "Der Unterschied zwischen Gut und Großartig? Konsistenz.", author: "" },
  { text: "90 Tage sind eine Entscheidung, nicht ein Wunsch.", author: "" },
  { text: "Du bist einen Schritt weiter als gestern. Das ist genug.", author: "" },
  { text: "Echte Transformation geschieht von innen.", author: "" },
  { text: "Dein Mindset ist dein wichtigster Muskel.", author: "" },
  { text: "Jeder Tag zählt. Auch der harte.", author: "" },
  { text: "Mach es nicht für die Likes — mach es für dich.", author: "" },
  { text: "Jede Verbesserung beginnt mit der Entscheidung, besser zu werden.", author: "" },
  { text: "Das Ziel ist nicht der Körper. Das Ziel ist der Mensch, der du dabei wirst.", author: "" },
  { text: "Entschlossenheit schlägt Talent.", author: "" },
  { text: "Du machst heute deinen Tag — niemand sonst.", author: "" },
  { text: "Der Körper folgt dem Mindset.", author: "" },
  { text: "90 Tage Fokus verändern dein ganzes Leben.", author: "" },
  { text: "Wer sich nicht entwickelt, bleibt stehen.", author: "" },
  { text: "Du hast alles, was du brauchst. Jetzt.", author: "" },
  { text: "Jeder Champion hat Tage, an denen er keine Lust hat. Und trainiert trotzdem.", author: "" },
  { text: "Wenn du glaubst, du kannst nicht mehr — dann fängst du gerade erst an.", author: "" },
  { text: "Die Version von dir in 90 Tagen wird dir danken.", author: "" },
  { text: "Du bist stärker als deine Ausreden.", author: "" },
  { text: "Was auch immer passiert — du trainierst heute.", author: "" },
  { text: "Ein erschöpfter Körper ist ein starker Beweis.", author: "" },
  { text: "Das Training beginnt, wenn es wehtut.", author: "" },
  { text: "Sei so konsequent wie ein Profi — auch wenn du noch kein Profi bist.", author: "" },
  { text: "Stärke baut sich nicht im Gym. Sie baut sich auf, wenn du trotzdem hingehst.", author: "" },
  { text: "Mittelmäßigkeit ist eine Wahl. Stärke ist eine Wahl. Wähle klug.", author: "" },
  { text: "Hunger nach Verbesserung ist der beste Treibstoff.", author: "" },
  { text: "Kein Stress, nur Wachstum.", author: "" },
  { text: "Träumen ist gut. Training ist besser.", author: "" },
  { text: "Ein Schritt nach dem anderen. Jeden Tag.", author: "" },
  { text: "Dein größter Feind bist du. Und dein größter Verbündeter auch.", author: "" },
  { text: "90 Tage können alles verändern. Fang jetzt an.", author: "" },
  { text: "Wer aufgibt, verliert immer. Wer durchhält, gewinnt meistens.", author: "" },
  { text: "Kein Schmerz heute, keine Veränderung morgen.", author: "" },
  { text: "Tue, was du liebst. Lerne zu lieben, was du tun musst.", author: "" },
  { text: "Großes entsteht aus kleinen, täglichen Taten.", author: "Vincent van Gogh" },
  { text: "Du weißt nicht, wie weit du gehen kannst, bis du anfängst zu gehen.", author: "" },
  { text: "Der einzige Weg ist nach vorne.", author: "" },
  { text: "Schreib dir jeden Tag gut, dass du etwas für deinen Körper getan hast.", author: "" },
  { text: "Sei die beste Version deiner selbst — jeden einzelnen Tag.", author: "" },
  { text: "Nur du entscheidest, wer du in 90 Tagen bist.", author: "" },
  { text: "Das Gym ist dein Beichtstuhl. Hier gibt es keine Lügen.", author: "" },
  { text: "Wer heute aufgibt, weiß nicht, was morgen möglich gewesen wäre.", author: "" },
  { text: "Stärke ist keine Körpereigenschaft — sie ist eine Gewohnheit.", author: "" },
  { text: "Leg los. Ohne Ausreden. Ohne Ausnahmen.", author: "" },
]

function getQuoteForDay(dayNr) {
  return QUOTES[(dayNr - 1) % QUOTES.length]
}
