const QUOTES = [
  { text: "Zähle nicht die Tage. Sorge dafür, dass jeder Tag zählt.", autor: "Muhammad Ali" },
  { text: "Der einzige schlechte Satz ist der, den du nicht gemacht hast.", autor: "" },
  { text: "Schmerz ist vorübergehend. Aufgeben ist für immer.", autor: "" },
  { text: "Was dich nicht umbringt, macht dich stärker.", autor: "Friedrich Nietzsche" },
  { text: "Harte Arbeit schlägt Talent, wenn Talent nicht hart arbeitet.", autor: "Tim Notke" },
  { text: "Vertraue dem Prozess. Die Ergebnisse folgen.", autor: "" },
  { text: "Dein Körper kann fast alles. Es ist dein Geist, den du überzeugen musst.", autor: "" },
  { text: "Die härteste Arbeit ist die, die du tust, wenn niemand zuschaut.", autor: "" },
  { text: "Jede Wiederholung bringt dich deinem Ziel näher.", autor: "" },
  { text: "Heute tust du, was andere nicht wollen. Morgen kannst du, was andere nicht können.", autor: "" },
  { text: "Fortschritt, nicht Perfektion.", autor: "" },
  { text: "Ein bisschen Fortschritt jeden Tag summiert sich zu großen Ergebnissen.", autor: "Robert Collier" },
  { text: "Sei die beste Version deiner selbst.", autor: "" },
  { text: "Wenn du aufgeben willst, erinnere dich daran, warum du angefangen hast.", autor: "" },
  { text: "Komfort ist der Feind des Fortschritts.", autor: "" },
  { text: "Jeder Champion war einmal ein Anfänger.", autor: "" },
  { text: "Stärke kommt nicht aus körperlicher Kapazität. Sie kommt aus einem unbeugsamen Willen.", autor: "Mahatma Gandhi" },
  { text: "Erfolg ist die Summe kleiner Bemühungen, täglich wiederholt.", autor: "Robert Collier" },
  { text: "Die Disziplin von heute ist die Stärke von morgen.", autor: "" },
  { text: "Dein zukünftiges Ich dankt dir für das, was du heute tust.", autor: "" },
  { text: "Der Geist gibt auf, lange bevor der Körper es tut.", autor: "" },
  { text: "Nicht wie du anfängst, sondern wie du endest, definiert dich.", autor: "" },
  { text: "Jeder Tag ist eine neue Chance, der Mensch zu werden, der du sein willst.", autor: "" },
  { text: "Gewinner hören nicht auf. Aufhörer gewinnen nicht.", autor: "" },
  { text: "Das Geheimnis des Erfolgs ist, anzufangen.", autor: "Mark Twain" },
  { text: "Es gibt keine Abkürzungen zu einem Ziel, das es wert ist zu erreichen.", autor: "" },
  { text: "Kleine tägliche Verbesserungen führen zu atemberaubenden Ergebnissen.", autor: "" },
  { text: "Der Körper erreicht, was der Geist glaubt.", autor: "" },
  { text: "Stark sein ist die einzige Option.", autor: "" },
  { text: "90 Tage. Konsequent. Kein Kompromiss.", autor: "Sjard Roscher" },
  { text: "Du bist nicht hier um durchschnittlich zu sein.", autor: "" },
  { text: "Schreib dir jeden Tag gut, dass du etwas für deinen Körper getan hast.", autor: "" },
  { text: "Wer aufhört, besser zu werden, hat aufgehört, gut zu sein.", autor: "" },
  { text: "Der einzige Weg ist nach vorne.", autor: "" },
  { text: "Schweiß ist Fett, das weint.", autor: "" },
  { text: "Mach es, auch wenn du keine Lust hast. Besonders dann.", autor: "" },
  { text: "Veränderung passiert außerhalb deiner Komfortzone.", autor: "" },
  { text: "Dein Körper ist das Ergebnis deiner täglichen Entscheidungen.", autor: "" },
  { text: "Du weißt nicht, wie weit du gehen kannst, bis du anfängst zu gehen.", autor: "" },
  { text: "Konsistenz schlägt Intensität. Immer.", autor: "" },
]

function getQuoteForDay(dayNr) {
  return QUOTES[(dayNr - 1) % QUOTES.length]
}
